Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2020-11, with the labels that each got.

#947 feat(MAQ): modifico position para no sobreponer footer
  src/components/shared/form/form-bulletin.vue
Labels: bug, dp6WebLandingEcommerce, needs-qa, pull-request

#953 feat(ECO): agrego campo dpto-ofic. para formulario de direcciones
  src/class/MercadoPago.js
  src/components/order/paymentsMethods/mercadopago.vue
  src/components/profile/address-data.vue
  src/components/profile/new-address-form.vue
  src/components/profile/user-order-details.vue
  src/components/shared/table/respondive-table.vue
Labels: dp6WebLandingEcommerce, needs-qa, pull-request

#951 feat(ECO): agrego estilos para responvise en detalle de pedido
  src/components/profile/user-order-details.vue
Labels: dp6WebLandingEcommerce, needs-qa, pull-request

#955 954: Agrego campos en formulario de nueva dirección
  index.html
  src/class/MercadoPago.js
  src/components/order/new-address.vue
  src/components/order/payment.vue
  src/components/order/paymentsMethods/mercadopago.vue
  src/components/order/summary-order.vue
  src/components/products/product-detail.vue
  src/components/products/product-view.vue
  src/components/profile/address-data.vue
  src/components/profile/new-address-form.vue
  src/components/profile/user-order-details.vue
  src/components/shared/account/account-form.vue
  src/components/shared/account/login-form.vue
  src/components/shared/form/form-bulletin.vue
  src/components/shared/table/respondive-table.vue
  src/filters/global.js
  src/pages/page-buy.vue
  src/pages/page-category.vue
  src/pages/page-login.vue
Labels: Perfil de Usuario, dp6WebLandingEcommerce, pull-request

#960 feat(conf): Corregir formulario al crear direccion
  src/components/order/new-address.vue
Labels: dp6WebLandingEcommerce, pull-request

#962 feat(INT): terminos y condiciones para niubiz
  src/components/order/paymentsMethods/niubiz.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#964 feat(INT): orden alfabetico en caracteristicas
  src/class/globalFeatures.js
  src/components/products/product-detail.vue
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request

#966 feat(INT): mostrar solo una imagen en detalle de producto
  src/class/productDetails.js
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request

#968 967: Calculo de costo de envío
  cypress/fixtures/fenix-dev.json
  cypress/integration/3.stockAndQuantity.spec.js
  cypress/integration/5.productsInCart.spec.js
  cypress/integration/6.shippingCost.spec.js
  cypress/support/commands.js
  src/components/order/new-address.vue
  src/filters/global.js
Labels: dp6WebLandingEcommerce, pull-request

#969 feat(INT): costo de envio al seleccionar direccion existente
  cypress/fixtures/fenix-dev.json
  cypress/integration/6.shippingCost.spec.js
  cypress/screenshots/examples/misc.spec.js/Misc -- cy.exec() - execute a system command (failed).png
  cypress/screenshots/examples/misc.spec.js/my-image.png
  cypress/videos/1.previousRouteAfterLogin.spec.js-compressed.mp4
  cypress/videos/1.previousRouteAfterLogin.spec.js.mp4
  cypress/videos/examples/waiting.spec.js.mp4
  src/components/order/delivery.vue
Labels: bug, dp6WebLandingEcommerce, pull-request

#971 feat(INT): creacion de pruebas adicionales sobre cantidad y stock en …
  cypress/fixtures/fenix-dev.json
  cypress/integration/3.stockAndQuantity.spec.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#972 feat(INT): direccion sin envio no habilita boton
  cypress/fixtures/fenix-dev.json
  cypress/integration/1.previousRouteAfterLogin.spec.js
  cypress/integration/6.shippingCost.spec.js
  cypress/support/commands.js
  src/components/order/new-address.vue
  src/pages/page-buy.vue
  src/store/actions.js
  src/store/getters/order.js
  src/store/mutations/order.js
  src/store/state.js
Labels: dp6WebLandingEcommerce, pull-request

#974 973: producto terminado
  cypress/fixtures/fenix-dev.json
  cypress/integration/1.previousRouteAfterLogin.spec.js
  cypress/integration/3.stockAndQuantity.spec.js
  cypress/integration/4.warehousesAvailability.spec.js
  cypress/integration/5.productsInCart.spec.js
  cypress/integration/6.shippingCost.spec.js
  cypress/integration/7.caracteristicasDetalleProducto.spec.js
  cypress/screenshots/examples/misc.spec.js/Misc -- cy.exec() - execute a system command (failed).png
  cypress/screenshots/examples/misc.spec.js/my-image.png
  cypress/support/commands.js
  cypress/videos/1.previousRouteAfterLogin.spec.js-compressed.mp4
  cypress/videos/1.previousRouteAfterLogin.spec.js.mp4
  cypress/videos/examples/waiting.spec.js.mp4
  src/class/globalFeatures.js
  src/class/productDetails.js
  src/components/order/delivery.vue
  src/components/order/new-address.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/paymentsMethods/niubiz.vue
  src/components/products/product-childrens.vue
  src/components/products/product-detail.vue
  src/filters/global.js
  src/pages/page-buy.vue
  src/pages/page-detail-product.vue
  src/store/actions.js
  src/store/getters/order.js
  src/store/mutations/order.js
  src/store/state.js
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request

#956 Migración
  cypress/fixtures/fenix-dev.json
  cypress/integration/3.stockAndQuantity.spec.js
  cypress/integration/4.warehousesAvailability.spec.js
  cypress/integration/5.productsInCart.spec.js
  cypress/integration/7.caracteristicasDetalleProducto.spec.js
  cypress/support/commands.js
  src/class/globalFeatures.js
  src/class/productDetails.js
  src/components/order/delivery.vue
  src/components/products/product-childrens.vue
  src/components/products/product-detail.vue
  src/components/profile/new-address-form.vue
  src/pages/page-detail-product.vue
  src/store/actions.js
Labels: Migración

#978 feat(INT): selecciono tienda si solo es una
  cypress/fixtures/fenix-dev.json
  cypress/integration/5.productsInCart.spec.js
  cypress/support/commands.js
  src/components/order/delivery.vue
  src/components/order/yape-component.vue
Labels: dp6WebLandingEcommerce, pull-request

#980 feat(INT): imagen del producto en carrito de compras
  cypress/integration/8.imagenDetalleProducto.spec.js
  cypress/support/commands.js
  src/class/productDetails.js
  src/components/products/product-view.vue
  src/components/shared/modal/app-modal.vue
Labels: Detalle de producto, carrito de compra, dp6WebLandingEcommerce, pull-request

#982 981: valido tipo de pago en resumen de pedido
  cypress/integration/5.productsInCart.spec.js
  cypress/integration/8.imagenDetalleProducto.spec.js
  cypress/support/commands.js
  src/components/order/credit-card-payment.js
  src/components/order/paymentsMethods/niubiz.vue
  src/pages/page-new-summary-order.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request
