Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2020-04, with the labels that each got.

#567 feat(INT): cambiar servicio
  .env.per
  package-lock.json
  package.json
  src/pages/page-login.vue
  src/pages/page-recover-password.vue
  src/pages/page-register.vue
  src/pages/page-restore-password.vue
  src/router/recover-password.js
Labels: dp6WebLandingEcommerce, needs-code-review, pull-request, qa-ready

#571 Migración
  .env.per
  package-lock.json
  package.json
  src/pages/page-login.vue
  src/pages/page-recover-password.vue
  src/pages/page-register.vue
  src/pages/page-restore-password.vue
  src/router/recover-password.js
Labels: Migración, qa-ready

#573 572: Enviar unidad por presentacion
  src/class/productDetails.js
  src/components/shared/category/list-category.vue
  src/pages/page-detail-product.vue
  src/shared/helper.js
Labels: dp6WebLandingEcommerce, needs-qa, pull-request
