Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2020-12, with the labels that each got.

#985 feat(INT): validacion cuando no existen imagenes
  cypress/integration/5.productsInCart.spec.js
  src/class/productDetails.js
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request

#986 feat(INT): correccion en costos de envio
  cypress/support/commands.js
  src/components/order/new-address.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#987 Costo envio
  cypress/fixtures/fenix-dev.json
  cypress/integration/6.shippingCost.spec.js
  cypress/integration/7.caracteristicasDetalleProducto.spec.js
  cypress/integration/8.imagenDetalleProducto.spec.js
  cypress/support/commands.js
  cypress/videos/1.previousRouteAfterLogin.spec.js-compressed.mp4
  cypress/videos/1.previousRouteAfterLogin.spec.js.mp4
  src/components/order/delivery.vue
  src/store/getters/order.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#988 feat(INT): corrijo nombre de action (vuex) setShippingCostError
  cypress/screenshots/1.previousRouteAfterLogin.spec.js/REGRESAR A PANTALLA PREVIA AL INICIO DE SESIÓN -- Iniciar sesión desde detalle de producto y regresar (failed).png
  cypress/screenshots/2.stockCeroSale.spec.js/PRODUCTO TIPO SERVICIO AL CARRITO DE COMPRAS -- Producto servicio sin stock al carrito de compras (failed).png
  cypress/videos/1.previousRouteAfterLogin.spec.js.mp4
  cypress/videos/1.stockCeroNoSale.spec.js.mp4
  cypress/videos/2.stockCeroSale.spec.js.mp4
  cypress/videos/3.stockAndQuantity.spec.js.mp4
  src/components/order/new-address.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#990 989: Costos de envío solo con tres valores de ubigeo
  cypress/fixtures/fenix-dev.json
  cypress/integration/6.shippingCost.spec.js
  cypress/support/commands.js
  src/components/order/deposit-payment.vue
  src/components/order/new-address.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#991 feat(INT): valido personName en resumen de pedido
  src/pages/page-new-summary-order.vue
Labels: blocking, bug, carrito de compra, dp6WebLandingEcommerce, pull-request

#993 feat(INT): meses de gracia y diferidos dinamicos
  cypress/screenshots/1.previousRouteAfterLogin.spec.js/REGRESAR A PANTALLA PREVIA AL INICIO DE SESIÓN -- Iniciar sesión desde detalle de producto y regresar (failed).png
  cypress/screenshots/2.stockCeroSale.spec.js/PRODUCTO TIPO SERVICIO AL CARRITO DE COMPRAS -- Producto servicio sin stock al carrito de compras (failed).png
  src/components/order/credit-card-payment.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
Labels: Data Fast, dp6WebLandingEcommerce, pull-request

#994 992: corrijo error: ahora se muestran tarjetas de crédito y diferidos
  src/components/order/paymentsMethods/data-fast.vue
Labels: Data Fast, carrito de compra, dp6WebLandingEcommerce, pull-request

#995 migración
  cypress/fixtures/fenix-dev.json
  cypress/integration/5.productsInCart.spec.js
  cypress/integration/6.shippingCost.spec.js
  cypress/integration/7.caracteristicasDetalleProducto.spec.js
  cypress/integration/8.imagenDetalleProducto.spec.js
  cypress/support/commands.js
  cypress/videos/1.previousRouteAfterLogin.spec.js-compressed.mp4
  cypress/videos/1.previousRouteAfterLogin.spec.js.mp4
  cypress/videos/1.stockCeroNoSale.spec.js.mp4
  cypress/videos/2.stockCeroSale.spec.js.mp4
  cypress/videos/3.stockAndQuantity.spec.js.mp4
  src/class/productDetails.js
  src/components/order/credit-card-payment.js
  src/components/order/delivery.vue
  src/components/order/deposit-payment.vue
  src/components/order/new-address.vue
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/paymentsMethods/niubiz.vue
  src/components/order/yape-component.vue
  src/components/products/product-conversions.vue
  src/components/products/product-view.vue
  src/components/shared/modal/app-modal.vue
  src/pages/page-new-summary-order.vue
  src/store/getters/order.js
Labels: Migración

#997 feat(INT): meses de diferimiento filtrados por activos
  src/components/order/paymentsMethods/data-fast.vue
Labels: Data Fast, carrito de compra, dp6WebLandingEcommerce, pull-request

#998 Migración
  src/components/order/paymentsMethods/data-fast.vue
Labels: Data Fast, Migración, carrito de compra, dp6WebLandingEcommerce

#1000 999
  src/components/order/delivery.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/store/getters/order.js
Labels: blocking, bug, carrito de compra, dp6WebLandingEcommerce, pull-request

#1001 migración
  src/components/order/delivery.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/store/getters/order.js
Labels: Migración

#1003 feat(INT): seleccion de almacen unico despues que vue actualiza
  src/components/order/delivery.vue
Labels: blocking, bug, dp6WebLandingEcommerce, pull-request

#1004 Migración
  src/components/order/delivery.vue
Labels: Migración

#1009 feat(INT): muestro tipo de moneda
  src/components/products/product-card.vue
Labels: dp6WebLandingEcommerce, pull-request

#1012 feat(INT): muestro imagenes de acuerdo a fromApp
  src/class/productDetails.js
  src/components/products/product-view.vue
  src/shared/lib.js
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request

#1010 Migración
  src/class/productDetails.js
  src/components/products/product-card.vue
  src/components/products/product-view.vue
  src/shared/lib.js
Labels: Migración

#1014 feat(INT): botones de caracteristicas
  cypress/integration/6.shippingCost.spec.js
  src/class/globalFeatures.js
  src/class/productDetails.js
  src/components/products/product-childrens.vue
  src/components/products/product-conversions.vue
  src/components/products/product-view.vue
  src/components/profile/address-data.vue
  src/components/profile/edit-user-data.vue
  src/pages/page-category.vue
  src/store/actions.js
  src/store/asyncActions.js
  src/store/getters/order.js
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request

#1005 feat(MAQ): mejoras en mostrar errores
  src/App.vue
  src/class/MercadoPago.js
  src/components/order/billing.vue
  src/components/order/delivery.vue
  src/components/order/new-address.vue
  src/components/order/paymentsMethods/mercadopago.vue
  src/components/products/form-opinion.vue
  src/components/products/product-card.vue
  src/components/products/product-detail.vue
  src/components/profile/address-data.vue
  src/components/profile/edit-user-data.vue
  src/components/profile/new-address-form.vue
  src/components/shared/modal/modal-component.vue
  src/http/index.js
  src/mixins/global.js
  src/pages/page-login.vue
  src/pages/page-new-summary-order.vue
  src/pages/page-recover-password.vue
  src/pages/page-register.vue
  src/pages/page-restore-password.vue
  src/store/state.js
Labels: dp6WebLandingEcommerce, pull-request

#1019 feat(INT): evito duplicidad de imagenes
  build/webpack.dev.conf.js
  config/dev.env.js
  config/prod.env.js
  index.html
  src/class/globalFeatures.js
  src/class/productDetails.js
  src/components/products/product-conversions.vue
  src/components/products/product-view.vue
  src/components/profile/address-data.vue
  src/components/profile/edit-user-data.vue
  src/pages/page-category.vue
  src/store/actions.js
  src/store/asyncActions.js
  src/store/getters/order.js
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request

#1022 feat(INT): muestro detalle de producto
  cypress/integration/5.productsInCart.spec.js
  cypress/integration/6.shippingCost.spec.js
  cypress/support/commands.js
  src/components/order/paymentsMethods/mercadopago.vue
  src/mixins/global.js
  src/store/asyncActions.js
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request

#1026 feat(INT): mantengo relacion 2 x 1 en banner
  src/components/home/banner-carousel.vue
  src/components/products/product-card.vue
  src/components/products/products-section.vue
  src/pages/page-components.vue
Labels: dp6WebLandingEcommerce, pull-request

#1029 feat(INT): actualizo mensaje cuando la cuenta no esta validada
  src/pages/page-login.vue
Labels: dp6WebLandingEcommerce, pull-request

#1032 feat(INT): validaciones para mercado pago
  src/class/MercadoPago.js
  src/components/order/paymentsMethods/mercadopago.vue
Labels: Mercado Pago, carrito de compra, dp6WebLandingEcommerce, pull-request

#1034 feat(INT): botones para pasar imagenes version movil
  src/components/products/product-view.vue
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request

#1036 feat(INT): cintillo de AGOTADO en los productos sin stock en detalle …
  cypress/fixtures/fenix-dev.json
  cypress/integration/3.stockAndQuantity.spec.js
  cypress/integration/5.productsInCart.spec.js
  cypress/integration/6.shippingCost.spec.js
  cypress/integration/7.caracteristicasDetalleProducto.spec.js
  cypress/integration/8.imagenDetalleProducto.spec.js
  cypress/videos/1.previousRouteAfterLogin.spec.js.mp4
  cypress/videos/1.stockCeroNoSale.spec.js.mp4
  cypress/videos/2.stockCeroSale.spec.js.mp4
  cypress/videos/3.stockAndQuantity.spec.js.mp4
  src/components/products/product-detail.vue
  src/components/products/product-view.vue
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request
