Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2020-06, with the labels that each got.

#623 feat(PAY): cuentas bancarias
  src/components/order/credit-card-payment.js
  src/components/order/deposit-payment.vue
  src/components/order/deposit-payments.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request, qa-ready

#628 feat(PRO): productos relacionados
  src/components/order/paymentsMethods/data-fast.vue
  src/pages/page-detail-product.vue
  src/store/asyncActions.js
  src/store/mutations.js
  src/store/state.js
Labels: Detalle de producto, dp6WebLandingEcommerce, pull-request, qa-ready

#621 feat(MAQ): Libro de reclamaciones - maquetacion
  a.js
  src/components/footer/app-footer.vue
  src/mixins/updateFromLocalStorage.js
  src/pages/page-reclamaciones.vue
  src/router/index.js
Labels: centro de ayuda, dp6WebLandingEcommerce, pull-request, qa-ready

#636 Migración
  a.js
  src/components/footer/app-footer.vue
  src/components/footer/section-visa.vue
  src/components/header/app-header.vue
  src/components/help/help-base.vue
  src/components/home/categories-carousel.vue
  src/components/order/credit-card-payment.js
  src/components/order/deposit-payment.vue
  src/components/order/deposit-payments.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/yape-component.vue
  src/components/profile/user-order-details.vue
  src/http/index.js
  src/mixins/loadResources.js
  src/mixins/updateFromLocalStorage.js
  src/pages/page-detail-product.vue
  src/pages/page-home.vue
  src/pages/page-reclamaciones.vue
  src/router/help.js
  src/router/index.js
  src/store/actions.js
  src/store/asyncActions.js
  src/store/getters.js
  src/store/mutations.js
  src/store/state.js
Labels: Migración

#642 feat(MAQ): correccion en lista de productos
  src/components/profile/user-order-details.vue
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#647 646: nueva estructura en costo de envio
  config/dev.env.js
  config/prod.env.js
  src/axios.js
  src/components/order/billing.vue
  src/components/order/delivery.vue
  src/components/order/new-address.vue
  src/components/order/responsible-form.vue
  src/components/order/summary-order.vue
  src/components/profile/user-order-details.vue
  src/components/shared/inputs/app-input.vue
  src/pages/page-category.vue
  src/pages/page-detail-product.vue
  src/shared/helper.js
  src/store/actions.js
  src/store/getters/order.js
  src/store/mutations/order.js
  src/store/state.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#653 652: Cambios solicitados por Ecu - ElMerkato
  src/components/order/billing.vue
  src/components/order/delivery.vue
  src/components/order/recieved-payment.vue
  src/components/order/responsible-form.vue
  src/components/profile/edit-user-data.vue
  src/mixins/global.js
  src/store/asyncActions.js
Labels: dp6WebLandingEcommerce, pull-request

#649 feat(INT): seccion de facturacion activa para ecuador
  src/components/order/billing.vue
  src/mixins/global.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#658 feat(INT): correccion de observaciones
  src/components/order/billing.vue
  src/components/order/delivery.vue
  src/components/order/deposit-payment.vue
  src/components/order/responsible-form.vue
  src/shared/enums/waysDeliveries.js
  src/shared/helper.js
  src/store/getters/order.js
Labels: dp6WebLandingEcommerce, pull-request

#657 feat(INT): agregar campo percentage
  src/shared/helper.js
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#659 Migración
  config/dev.env.js
  config/prod.env.js
  src/axios.js
  src/components/order/billing.vue
  src/components/order/delivery.vue
  src/components/order/deposit-payment.vue
  src/components/order/new-address.vue
  src/components/order/recieved-payment.vue
  src/components/order/responsible-form.vue
  src/components/profile/edit-user-data.vue
  src/components/shared/inputs/app-input.vue
  src/mixins/global.js
  src/shared/enums/waysDeliveries.js
  src/shared/helper.js
  src/store/actions.js
  src/store/asyncActions.js
  src/store/getters/order.js
  src/store/mutations/order.js
  src/store/state.js
Labels: Migración

#661 660: Selección de tipos de entrega
  src/components/order/delivery.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request, qa-ready

#663 662: costo de envío y almacén en detalle de pedido
  src/components/order/delivery.vue
  src/components/order/new-address.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/shared/helper.js
  src/store/actions.js
  src/store/mutations/order.js
  src/store/state.js
Labels: bug, dp6WebLandingEcommerce, pull-request, qa-ready

#664 Production => dev
  src/components/order/delivery.vue
  src/components/order/new-address.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/shared/helper.js
  src/store/actions.js
  src/store/mutations/order.js
  src/store/state.js
Labels: Migración, dp6WebLandingEcommerce

#666 feat(INT): costo de envio actualizado al cambiar tipo de envio.
  src/components/order/billing.vue
  src/components/order/new-address.vue
  src/store/actions.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#667 Production => dev
  src/components/order/billing.vue
  src/components/order/new-address.vue
  src/store/actions.js
Labels: Migración, dp6WebLandingEcommerce, pull-request

#673 feat(INT): monstar datos de la cuenta bancaria
  src/components/order/deposit-payment.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request, qa-ready

#676 675: stilos en diferentes pantallas - carrito de compras
  src/class/globalFeatures.js
  src/class/productDetails.js
  src/components/order/billing.vue
  src/components/order/delivery.vue
  src/components/order/deposit-payment.vue
  src/components/order/payment.vue
  src/components/order/paymentsMethods/paymentez.vue
  src/components/order/products-buyed.vue
  src/components/order/summary-in-payment.vue
  src/components/order/summary-order.vue
  src/components/products/product-in-car.vue
  src/components/shared/inputs/app-input-search.vue
  src/mixins/loadResources.js
  src/mixins/updateFromLocalStorage.js
  src/pages/page-buy.vue
  src/pages/page-category.vue
  src/store/actions.js
  src/store/asyncActions.js
  src/store/getters/order.js
  src/store/mutations.js
  src/store/mutations/order.js
  src/store/state.js
Labels: CORRECIÓN, carrito de compra, dp6WebLandingEcommerce, pull-request, qa-ready

#671 feat(INT): falgGrouper y selector de tipo de documento
  src/components/order/billing.vue
  src/pages/page-category.vue
  src/store/actions.js
  src/store/asyncActions.js
  src/store/mutations.js
  src/store/state.js
Labels: CORRECIÓN, dp6WebLandingEcommerce, pull-request

#679 Migración
  src/class/globalFeatures.js
  src/class/productDetails.js
  src/components/order/billing.vue
  src/components/order/delivery.vue
  src/components/order/deposit-payment.vue
  src/components/order/payment.vue
  src/components/order/paymentsMethods/paymentez.vue
  src/components/order/products-buyed.vue
  src/components/order/summary-in-payment.vue
  src/components/order/summary-order.vue
  src/components/products/product-in-car.vue
  src/components/shared/inputs/app-input-search.vue
  src/mixins/loadResources.js
  src/mixins/updateFromLocalStorage.js
  src/pages/page-buy.vue
  src/pages/page-category.vue
  src/store/actions.js
  src/store/asyncActions.js
  src/store/getters/order.js
  src/store/mutations.js
  src/store/mutations/order.js
  src/store/state.js
Labels: Migración, dp6WebLandingEcommerce, qa-ready
