Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2020-10, with the labels that each got.

#856 feat(ECO): agrego codigo para mostrar diferidos y tipos de crédito
  package-lock.json
  src/components/order/deposit-payments.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
  static/icons/informacion.svg
Labels: dp6WebLandingEcommerce, needs-qa, pull-request

#854 feat(ECO): mostrar información de tarjetas de datafast
  package-lock.json
  src/components/order/deposit-payments.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
  static/icons/informacion.svg
Labels: dp6WebLandingEcommerce, needs-qa, pull-request

#851 feat(INT): observaciones
  src/components/header/app-category.vue
  src/components/profile/user-orders.vue
  src/components/shared/products/media-filter-product.vue
  src/pages/page-login.vue
  src/store/asyncActions.js
Labels: dp6WebLandingEcommerce, pull-request

#858 feat(INT): agrego variable de entorno para opacidad en carrusel de ca…
  config/dev.env.js
  config/prod.env.js
  src/components/header/app-category.vue
  src/components/home/categories-carousel.vue
  src/components/products/product-detail.vue
Labels: dp6WebLandingEcommerce, pull-request

#876 feat(eco): Deshabilitar botón de "datafast" mientras se este cargando el modal
  package-lock.json
  src/App.vue
  src/components/order/credit-card-payment.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#881 feat(bug): corregir variable en dataFast
  src/components/order/paymentsMethods/data-fast.vue
Labels: CORRECIÓN, dp6WebLandingEcommerce

#883 feat(maq) : corregir icono data fast y listado tarjeta a pagar
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
  static/icons/information.svg
Labels: dp6WebLandingEcommerce, pull-request

#848 847: Actualizar ramas `dev`, `production`, `production-fintimas`
  config/dev.env.js
  config/prod.env.js
  cypress/integration/1.previousRouteAfterLogin.spec.js
  cypress/integration/5.productsInCart.spec.js
  cypress/support/commands.js
  src/axios.js
  src/components/header/app-category.vue
  src/components/header/app-header.vue
  src/components/header/modal-login.vue
  src/components/home/categories-carousel.vue
  src/components/order/paymentsMethods/place-to-pay.vue
  src/components/order/responsible-form.vue
  src/components/products/product-card.vue
  src/components/products/product-detail.vue
  src/components/products/product-in-car.vue
  src/components/profile/edit-user-data.vue
  src/components/profile/online-transactions.vue
  src/components/profile/user-data-details.vue
  src/components/profile/user-order-details.vue
  src/components/profile/user-orders.vue
  src/components/shared/account/register-form.vue
  src/components/shared/company/container-company-data.vue
  src/components/shared/company/media-company-data.vue
  src/mixins/userDataValidation.js
  src/pages/page-detail-product.vue
  src/pages/page-login.vue
  src/pages/page-register.vue
  src/store/asyncActions.js
  static/img/creditCards/Visa_Inc._logo.svg.png
  static/img/creditCards/american.svg
  static/img/creditCards/dinners.svg
  static/img/creditCards/discover.jpg
  static/img/creditCards/discover.png
  static/img/creditCards/mastercard.svg
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#884 migración
  cypress/integration/1.previousRouteAfterLogin.spec.js
  cypress/integration/4.productsInCart.spec.js
  cypress/integration/4.warehousesAvailability.spec.js
  cypress/integration/5.productsInCart.spec.js
  cypress/support/commands.js
  package-lock.json
  src/App.vue
  src/axios.js
  src/components/header/app-category.vue
  src/components/header/app-header.vue
  src/components/header/modal-login.vue
  src/components/home/categories-carousel.vue
  src/components/order/credit-card-payment.js
  src/components/order/deposit-payments.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/paymentsMethods/place-to-pay.vue
  src/components/order/responsible-form.vue
  src/components/order/summary-order.vue
  src/components/products/product-buy.vue
  src/components/products/product-card.vue
  src/components/products/product-childrens.vue
  src/components/products/product-detail.vue
  src/components/products/product-in-car.vue
  src/components/products/warehouses-modal.vue
  src/components/profile/edit-user-data.vue
  src/components/profile/online-transactions.vue
  src/components/profile/user-data-details.vue
  src/components/profile/user-order-details.vue
  src/components/profile/user-orders.vue
  src/components/shared/account/register-form.vue
  src/components/shared/company/container-company-data.vue
  src/components/shared/company/media-company-data.vue
  src/components/shared/products/media-filter-product.vue
  src/mixins/userDataValidation.js
  src/pages/page-detail-product.vue
  src/pages/page-login.vue
  src/pages/page-register.vue
  src/store/asyncActions.js
  static/icons/informacion.svg
  static/icons/information.svg
  static/img/creditCards/Visa_Inc._logo.svg.png
  static/img/creditCards/american.svg
  static/img/creditCards/dinners.svg
  static/img/creditCards/discover.jpg
  static/img/creditCards/discover.png
  static/img/creditCards/mastercard.svg
Labels: Migración

#886 feat(INT): cambio de imagenes con tamano de pantalla
  src/components/home/banner-carousel.vue
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#887 Migración
  src/components/home/banner-carousel.vue
Labels: Migración

#888 feat(maq): corregir datafast
  config/dev.env.js
  config/prod.env.js
  src/components/order/paymentsMethods/data-fast.vue
Labels: dp6WebLandingEcommerce

#889 Migración
  config/dev.env.js
  config/prod.env.js
  src/components/order/paymentsMethods/data-fast.vue
Labels: Migración

#891 feat(INT): oculto icono cuando no hay opacidad en la categoria
  src/components/home/categories-carousel.vue
Labels: dp6WebLandingEcommerce, pull-request

#892 Migración
  src/components/home/categories-carousel.vue
Labels: Migración

#896 feat(INT): observaciones Eterna
  config/dev.env.js
  config/prod.env.js
  src/components/header/app-header.vue
  src/components/header/item-menu.vue
  src/components/home/categories-carousel.vue
  src/pages/page-category.vue
Labels: dp6WebLandingEcommerce, pull-request, topic

#897 Migración
  config/dev.env.js
  config/prod.env.js
  src/components/header/app-header.vue
  src/components/header/item-menu.vue
  src/components/home/categories-carousel.vue
  src/pages/page-category.vue
Labels: Migración

#899 faet(INT): observaciones generales
  src/components/help/help-content.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/products-buyed.vue
  src/components/shared/form/form-bulletin.vue
  src/components/shared/modal/app-modal.vue
  src/filters/global.js
Labels: dp6WebLandingEcommerce, pull-request

#900 Migración
  src/components/help/help-content.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/products-buyed.vue
  src/components/shared/form/form-bulletin.vue
  src/components/shared/modal/app-modal.vue
  src/filters/global.js
Labels: Migración

#894 feat(eco): validar seccion mostrar tarjetas a pagar con datafast
  src/components/order/payment.vue
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#905 feat(INT): muestro descripcion de categoria
  src/components/header/app-category.vue
Labels: dp6WebLandingEcommerce, pull-request

#909 feat(ECO): modifico y valido muestra de informacion en menu categorias
  src/components/header/app-category.vue
Labels: dp6WebLandingEcommerce, needs-qa, pull-request

#826 feat(INT): elimino variables de paymentez al editar pedido
  src/components/order/paymentsMethods/paymentez.vue
  src/shared/helper.js
  src/store/actions.js
Labels: dp6WebLandingEcommerce, pull-request

#906 feat(ECO): agrego validacion para evitar error al seleccionar variaciones
  src/class/productDetails.js
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#911 Migración
  src/class/productDetails.js
  src/components/header/app-category.vue
  src/components/order/credit-card-payment.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/alignet.vue
  src/components/order/paymentsMethods/paymentez.vue
  src/shared/enums/gatewayCodes.js
  src/shared/helper.js
  src/store/actions.js
Labels: Migración

#805 783: integració niubiz
  src/components/order/credit-card-payment.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/niubiz.vue
  src/components/order/paymentsMethods/pago-plux.vue
  src/components/products/product-card.vue
  src/components/shared/category/list-category.vue
  src/pages/page-new-summary-order.vue
  src/shared/enums/gatewayCodes.js
  src/store/getters.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#913 Migración
  src/components/order/credit-card-payment.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/niubiz.vue
  src/components/order/paymentsMethods/pago-plux.vue
  src/components/products/product-card.vue
  src/components/shared/category/list-category.vue
  src/pages/page-new-summary-order.vue
  src/shared/enums/gatewayCodes.js
  src/store/getters.js
Labels: Migración

#915 feat(MAQ): mostrar descripcion, agrandar precio anterior y eliminar +…
  src/components/products/product-card.vue
Labels: dp6WebLandingEcommerce, pull-request

#916 migració
  src/components/products/product-card.vue
Labels: Migración

#919 918: botón de pago Mercado Pago
  src/class/MercadoPago.js
  src/components/order/credit-card-payment.js
  src/components/order/paymentsMethods/mercadopago.vue
  src/shared/enums/gatewayCodes.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#920 Migración mercadopago
  src/class/MercadoPago.js
  src/components/order/credit-card-payment.js
  src/components/order/paymentsMethods/mercadopago.vue
  src/shared/enums/gatewayCodes.js
Labels: Migración

#922 feat(INT): errores en mercadopago
  src/class/MercadoPago.js
Labels: Mercado Pago, carrito de compra, dp6WebLandingEcommerce, pull-request

#923 Migración
  src/class/MercadoPago.js
Labels: Migración

#924 917: mostrar datos de la tarjeta Niubiz
  src/components/order/paymentsMethods/niubiz.vue
  src/pages/page-buy.vue
  src/pages/page-new-summary-order.vue
  src/router/buy.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#908 feat(eco): mostrar sección "tarjetas con las que puedes pagar data fast"
  src/components/order/payment.vue
Labels: dp6WebLandingEcommerce, qa-ready

#925 Migración
  src/components/order/payment.vue
  src/components/order/paymentsMethods/niubiz.vue
  src/pages/page-buy.vue
  src/pages/page-new-summary-order.vue
  src/router/buy.js
  src/stylesheets/variables.scss
Labels: Migración

#927 feat(REV): flujo funciona. Version movil de formulario fatal. Fue sol…
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/paymentsMethods/mercadopago.vue
  src/components/order/paymentsMethods/niubiz.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#928 Migración
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/paymentsMethods/mercadopago.vue
  src/components/order/paymentsMethods/niubiz.vue
Labels: Migración

#931 Migración
  src/App.vue
  src/class/MercadoPago.js
  src/components/order/paymentsMethods/mercadopago.vue
  src/components/profile/address-data.vue
  src/components/profile/favorites.vue
  src/components/profile/online-transactions.vue
  src/components/shared/category/filters-category.vue
  src/components/shared/category/list-category.vue
  src/components/shared/table/respondive-table.vue
Labels: Migración

#932 Migreación
  src/components/order/summary-order.vue
Labels: Migración

#934 feat(ECO): Cambiar icono de perfil
  src/App.vue
  src/components/header/app-header.vue
  src/components/order/summary-order.vue
  src/mixins/global.js
  src/store/state.js
Labels: dp6WebLandingEcommerce, pull-request

#936 feat(MAQ): Redireccionar al loguin
  src/components/order/summary-order.vue
Labels: dp6WebLandingEcommerce, needs-qa, pull-request

#938 937: Cambio funcionalidad para mostrar inicio sesión en safari versión móvil
  src/App.vue
  src/components/header/app-header.vue
  src/components/order/summary-order.vue
  src/mixins/global.js
  src/store/state.js
Labels: dp6WebLandingEcommerce, pull-request

#939 Migración
  src/components/order/summary-order.vue
Labels: Migración

#942 feat(INT): flujo inicio sesion con facebook
  src/components/order/summary-order.vue
  src/components/products/product-view.vue
  src/components/shared/account/account-form.vue
  src/components/shared/account/login-form.vue
  src/pages/page-login.vue
Labels: bug, dp6WebLandingEcommerce, pull-request

#943 Facebook redirecciona a /carrito-de-compras
  src/components/order/summary-order.vue
  src/components/shared/account/account-form.vue
Labels: bug, carrito de compra, dp6WebLandingEcommerce, pull-request

#944 feat(INT): no se muestra cero en precio de producto. se muestra Carga…
  src/components/products/product-detail.vue
  src/filters/global.js
  src/pages/page-category.vue
Labels: Categoría, Detalle de producto, dp6WebLandingEcommerce, pull-request
