Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2020-07, with the labels that each got.

#693 692: corrección en sitio de recojo / entrega
  src/App.vue
  src/components/header/app-header.vue
  src/components/order/delivery.vue
  src/components/shared/buttons/app-button.vue
  src/mixins/global.js
  src/shared/helper.js
  src/store/actions.js
  src/store/mutations/order.js
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#695 694: bankAccountId = null
  src/App.vue
  src/components/header/app-header.vue
  src/components/order/delivery.vue
  src/components/shared/buttons/app-button.vue
  src/mixins/global.js
  src/shared/helper.js
  src/store/actions.js
  src/store/mutations/order.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#690 689: Integración de pasarela
  index.html
  src/App.vue
  src/class/globalFeatures.js
  src/components/order/credit-card-payment.js
  src/components/order/deposit-payment.vue
  src/components/order/payment.vue
  src/components/order/paymentsMethods/paymentez.vue
  src/components/order/paymentsMethods/xchange.vue
  src/components/profile/user-data-details.vue
  src/router/buy.js
  src/shared/enums/wayPayment.js
  src/shared/lib.js
  src/store/asyncActions.js
  src/store/getters/order.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request, qa-ready

#683 feat(MAQ): archivo unico para xchange
  src/components/order/credit-card-payment.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/xchange.vue
Labels: carrito de compra, dp6WebLandingEcommerce, needs-qa, pull-request

#696 migración
  index.html
  src/App.vue
  src/class/globalFeatures.js
  src/components/order/credit-card-payment.js
  src/components/order/delivery.vue
  src/components/order/deposit-payment.vue
  src/components/order/payment.vue
  src/components/order/paymentsMethods/paymentez.vue
  src/components/order/paymentsMethods/xchange.vue
  src/components/profile/user-data-details.vue
  src/router/buy.js
  src/shared/enums/wayPayment.js
  src/shared/helper.js
  src/shared/lib.js
  src/store/asyncActions.js
  src/store/getters/order.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#701 feat(help): Agregar campo descripción en el centro de ayuda
  src/components/help/help-base.vue
  src/components/help/help-content.vue
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#705 feat(INT): se muestra formulario para peru
  src/components/order/billing.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request, qa-ready

#707 Migración
  src/components/help/help-base.vue
  src/components/help/help-content.vue
  src/components/order/billing.vue
Labels: dp6WebLandingEcommerce, qa-ready, topic

#708 feat(INT): correccion de observaciones
  src/pages/page-reclamaciones.vue
Labels: centro de ayuda, dp6WebLandingEcommerce, pull-request, qa-ready

#710 feat(INT): banners version movil y web
  src/components/home/banner-carousel.vue
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#713 Migración
  package-lock.json
  src/components/home/banner-carousel.vue
  src/pages/page-reclamaciones.vue
Labels: Migración, qa-ready

#716 715: PagoPlux
  a.js
  index.html
  src/components/order/credit-card-payment.js
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/paymentsMethods/leadgods.vue
  src/components/order/paymentsMethods/pago-plux.vue
  src/components/order/paymentsMethods/paymentez.vue
  src/components/order/paymentsMethods/place-to-pay.vue
  src/components/order/paymentsMethods/xchange.vue
  src/components/products/product-tab.vue
  src/shared/enums/paymentStrategy.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#718 Migración
  a.js
  index.html
  src/components/order/credit-card-payment.js
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/paymentsMethods/leadgods.vue
  src/components/order/paymentsMethods/pago-plux.vue
  src/components/order/paymentsMethods/paymentez.vue
  src/components/order/paymentsMethods/place-to-pay.vue
  src/components/order/paymentsMethods/xchange.vue
  src/components/products/product-tab.vue
  src/shared/enums/paymentStrategy.js
Labels: Migración, pull-request
