Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2020-05, with the labels that each got.

#579 578: obtener datos de facturación desde typePerson
  package-lock.json
  package.json
  src/components/order/payment.vue
  src/components/order/thanks-message.vue
  src/components/shared/account/register-form.vue
  src/pages/page-login.vue
  src/pages/page-register.vue
  src/store/actions.js
  src/store/index.js
  src/store/modules/login/index.js
Labels: dp6WebLandingEcommerce, pull-request, qa-ready

#580 migración
  package-lock.json
  package.json
  src/components/order/payment.vue
  src/components/order/thanks-message.vue
  src/store/actions.js
Labels: Migración, dp6WebLandingEcommerce, qa-ready

#583 feat(MAQ): creacion de componente datafast
  src/components/order/credit-card-payment.js
  src/components/order/payment.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/components/order/paymentsMethods/visa-payment.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#585 feat(PAY): se muesta formulario datafast
  config/dev.env.js
  config/prod.env.js
  src/components/order/paymentsMethods/data-fast.vue
Labels: dp6WebLandingEcommerce, pull-request

#589 feat(MAQ): eliminar codigo comentado
  src/components/order/paymentsMethods/data-fast.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#593 590: redirección
  src/components/help/help-base.vue
  src/components/help/help-content.vue
  src/components/order/paymentsMethods/data-fast.vue
  src/pages/page-help-center.vue
  src/pages/page-not-found.vue
  src/router/help.js
  src/router/index.js
Labels: centro de ayuda, dp6WebLandingEcommerce, pull-request

#594 feat(MAQ): maquetar nueva estructura de centro de ayuda
  src/components/help/help-content.vue
Labels: centro de ayuda, dp6WebLandingEcommerce, pull-request

#596 feat(MAQ): ruteo
  src/components/footer/section-links.vue
  src/components/help/help-base.vue
  src/components/shared/not-found.vue
  src/pages/page-not-found.vue
  src/router/help.js
  src/router/index.js
Labels: centro de ayuda, dp6WebLandingEcommerce, pull-request

#602 601: vesión móvil
  src/components/footer/section-links.vue
  src/components/help/help-base.vue
  src/components/help/help-content.vue
  src/pages/page-help-center.vue
  src/router/help.js
Labels: centro de ayuda, dp6WebLandingEcommerce, pull-request

#600 feat(HEL): recargar y mantener informacion
  src/components/footer/section-links.vue
  src/components/help/help-base.vue
  src/components/help/help-content.vue
  src/router/help.js
Labels: centro de ayuda, dp6WebLandingEcommerce, pull-request

#605 feat(PAY): checkout al presionar boton
  src/components/order/paymentsMethods/data-fast.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#607 feat(PAY): boton yape
  README.md
  src/components/order/deposit-payment.vue
  src/components/order/deposit-payments.js
  src/components/order/yape-component.vue
  src/shared/enums/wayPayment.js
  src/store/getters.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#614 613: modal de éxito
  src/components/order/deposit-payments.js
  src/components/order/yape-component.vue
  src/components/svg/success.vue
  src/shared/enums/depositPayment.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request, qa-ready

#612 611: Mostrar imagen por servicio
  src/components/order/deposit-payments.js
  src/components/order/yape-component.vue
  src/components/svg/success.vue
  src/shared/enums/depositPayment.js
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#610 feat(PAY): maquetar modal de pago yape
  src/components/order/yape-component.vue
Labels: carrito de compra, dp6WebLandingEcommerce, pull-request

#619 feat(MAQ): eliminar medios de pago
  src/components/footer/section-links.vue
Labels: dp6WebLandingEcommerce, pull-request

#618 feat(HOM): banners y categorias por comercio
  src/components/help/help-base.vue
  src/mixins/loadResources.js
  src/router/help.js
  src/store/asyncActions.js
Labels: dp6WebLandingEcommerce, pull-request
