Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2021-11, with the labels that each got.

#1125 feat:(BUG) Bug error en ecommerce Se permite editar pedidos ya finalizados
  src/http/errors.js
  src/store/asyncActions.js
Labels: bug, pull-request, dp6WebLandingEcommerce

#1128 feat:(COM) Poder Agregar comentario en el pedido
  src/components/order/delivery.vue
  src/components/products/product-in-car.vue
  src/components/profile/user-order-details.vue
  src/shared/helper.js
  src/store/actions.js
  src/store/getters/order.js
  src/store/mutations/order.js
  src/store/state.js
Labels: pull-request, dp6WebLandingEcommerce

#1129 Pase a Produccion
  src/class/productDetails.js
  src/components/order/delivery.vue
  src/components/products/product-card.vue
  src/components/products/product-in-car.vue
  src/components/products/products-section.vue
  src/components/profile/user-order-details.vue
  src/components/shared/icons/addcar-component.vue
  src/components/shared/spinner/spinner-loading.vue
  src/http/errors.js
  src/pages/page-buy.vue
  src/pages/page-category.vue
  src/pages/page-detail-product.vue
  src/pages/page-profile.vue
  src/shared/helper.js
  src/store/actions.js
  src/store/asyncActions.js
  src/store/getters.js
  src/store/getters/order.js
  src/store/mutations.js
  src/store/mutations/order.js
  src/store/state.js
Labels: pull-request, dp6WebLandingEcommerce

#1135 feat:(PRO) Al agregar al carrito de compra sale un mensaje verde que impide ver si he agregado al carrito.
  src/class/productDetails.js
  src/components/footer/cart-bottom.vue
  src/components/header/app-header.vue
  src/components/products/product-card.vue
  src/components/products/product-conversions.vue
  src/components/products/product-detail.vue
  src/components/shared/icons/addcar-component.vue
  src/pages/page-category.vue
  src/pages/page-detail-product.vue
  src/pages/page-home.vue
  src/store/actions.js
  src/store/getters/order.js
Labels: pull-request, dp6WebLandingEcommerce

#1138 feat(mej): corregir en el carrito de compras el footer no pase la informacion del pedido
  src/components/order/summary-order.vue
  src/components/products/product-view.vue
  src/pages/page-buy.vue
Labels: pull-request, dp6WebLandingEcommerce

#1143 feat:(PRO) (PRO) Reducir el tamaño del Bottom flotante y almacenar el teléfono del cliente en los pagos
  src/components/footer/cart-bottom.vue
  src/components/order/responsible-form.vue
  src/components/order/summary-order.vue
  src/components/products/product-card.vue
  src/pages/page-buy.vue
  src/shared/helper.js
Labels: pull-request, dp6WebLandingEcommerce

#1145 feat(mej): Agregar unidades en mobile
  src/components/products/product-conversion-header.vue
  src/components/products/product-view.vue
  src/pages/page-detail-product.vue
Labels: pull-request, dp6WebLandingEcommerce

#1149 feat:(PRO) Agregar diseño del boton confirmar cantidades en base al zeplin
  src/components/footer/cart-bottom.vue
Labels: dp6WebLandingEcommerce, issue

#1150 feat(mej): Validar segun el fromApp mostrar la imagen
  src/App.vue
  src/components/products/product-conversions.vue
  src/components/products/product-view.vue
  src/pages/page-detail-product.vue
Labels: pull-request, dp6WebLandingEcommerce

#1153 feat(bug): Mostrar el total en el modal al agregar la cantidad en el detalle de producto
  src/components/shared/modal/app-modal.vue
Labels: pull-request, dp6WebLandingEcommerce
