Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2021-09, with the labels that each got.

#1101 feat(maq): Agregar funcionalidad en el carrito de compras
  package-lock.json
  src/components/order/new-address.vue
  src/components/products/product-buy.vue
  src/components/products/product-conversions.vue
  src/components/products/product-detail.vue
  src/components/products/product-in-car.vue
  src/components/shared/buttons/app-button-order.vue
  src/components/shared/buttons/quantity-button.vue
  src/pages/page-buy.vue
  src/pages/page-detail-product.vue
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
Labels: dp6WebLandingEcommerce

#1102 Pase a prod 3/09
  package-lock.json
  src/components/order/new-address.vue
  src/components/products/product-buy.vue
  src/components/products/product-conversions.vue
  src/components/products/product-detail.vue
  src/components/products/product-in-car.vue
  src/components/shared/buttons/app-button-order.vue
  src/components/shared/buttons/quantity-button.vue
  src/pages/page-buy.vue
  src/pages/page-detail-product.vue
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
Labels: deployment, dp6WebLandingEcommerce

#1105 Pase a Prod 17/09
  src/pages/page-detail-product.vue
  src/pages/page-reclamaciones.vue
Labels: pull-request, dp6WebLandingEcommerce

#1111 feat(mej): Mejoras al realizar pedidos
  src/components/order/paymentsMethods/place-to-pay.vue
  src/components/order/paymentsMethods/xchange.vue
  src/pages/page-buy.vue
  src/pages/page-new-summary-order.vue
Labels: pull-request, dp6WebLandingEcommerce
