Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2024-02, with the labels that each got.

#1337 Feat(Clean Input and Reload products in home
  .eslintrc.js
  build/utils.js
  src/components/header/app-header.vue
  src/components/shared/inputs/app-input-search.vue
  src/stylesheets/index.scss
Labels: pull-request, needs-qa

#1339 Feat(SAL)[5]: Vender con stock negativo
  src/components/header/app-header.vue
  src/main.js
  src/pages/page-detail-product.vue
  src/shared/helper.js
  src/store/asyncActions.js
  src/store/mutations/order.js
Labels: issue

#1344 Feat(CONF): Fix add producto stockIlimitado
  src/store/actions.js
Labels: pull-request, needs-qa

#1346 Feat: Mostrar CCI
  src/components/order/deposit-payment.vue
Labels: pull-request

#1348 Feat: validacion UND al mostrar
  src/components/products/product-conversions.vue
  src/components/products/product-detail.vue
  src/main.js
Labels: pull-request
