Repository apprunn/dp6WebLandingEcommerce, pull requests merged in 2025-07, with the labels that each got.

#1411 feat: No funciona la opcion de precio por mayor
  src/components/footer/cart-bottom.vue
  src/components/products/product-buy.vue
  src/components/products/product-detail.vue
  src/components/products/product-in-car.vue
  src/components/shared/modal/app-modal.vue
  src/pages/page-detail-product.vue
  src/shared/helper.js
  src/store/getters/order.js
Labels: CORRECIÓN

#1433 fix: Validar la lista de precio al crear el pedido
  src/shared/helper.js
Labels: qa-ready

#1432 Validar mostrar und principal o conversiones al agregar prod al carrito
  src/components/products/product-card.vue
Labels: Done

#1430 Validar correctamente la cantidad disponible a vender segun el stock por tipo
  src/components/products/product-card.vue
  src/components/products/product-detail.vue
  src/components/products/product-in-car.vue
  src/mixins/global.js
  src/mixins/loadResources.js
  src/pages/page-buy.vue
  src/pages/page-detail-product.vue
  src/shared/helper.js
  src/store/actions.js
  src/store/mutations/order.js
Labels: Done

#1434 Fix load domains
  .eslintrc.js
  src/axios.js
  src/components/footer/cart-bottom.vue
  src/components/products/product-buy.vue
  src/components/products/product-card.vue
  src/components/products/product-detail.vue
  src/components/products/product-in-car.vue
  src/components/shared/modal/app-modal.vue
  src/http/errors.js
  src/http/http-factory.js
  src/http/index.js
  src/http/interceptors-factory.js
  src/http/plugin.js
  src/main.js
  src/mixins/global.js
  src/mixins/loadResources.js
  src/pages/page-buy.vue
  src/pages/page-detail-product.vue
  src/shared/helper.js
  src/store/actions.js
  src/store/asyncActions.js
  src/store/getters/order.js
  src/store/mutations/order.js
Labels: qa-ready

#1435 Correguir actualizar el precio por rango en carrito
  .eslintrc.js
  src/axios.js
  src/components/products/product-in-car.vue
  src/http/errors.js
  src/http/http-factory.js
  src/http/index.js
  src/http/interceptors-factory.js
  src/http/plugin.js
  src/main.js
  src/mixins/global.js
  src/mixins/loadResources.js
  src/pages/page-detail-product.vue
  src/shared/helper.js
  src/store/actions.js
  src/store/asyncActions.js
  src/store/mutations/order.js
  src/stylesheets/fonts.scss
  src/stylesheets/index.scss
Labels: qa-ready
